typedef int WINAPI (*tf_PSGetUSBDevNum)(int*);
typedef int WINAPI (*tf_PSGetUDiskNum)(int* );
typedef int WINAPI (*tf_PSOpenDeviceEx)(HANDLE* , int ,int ,int ,int ,int );
typedef int WINAPI (*tf_PSCloseDeviceEx)(HANDLE );
typedef int WINAPI (*tf_JPSetPackSize)(HANDLE , int );
typedef int WINAPI (*tf_PSAutoOpen)(HANDLE* ,int *, int ,UINT ,int );
typedef int WINAPI (*tf_PSGetImage)(HANDLE ,int );
typedef int WINAPI (*tf_PSGetImage_Enroll)(HANDLE ,int );
typedef int WINAPI (*tf_PSGenChar)(HANDLE ,int ,int );
typedef int WINAPI (*tf_PSMatch)(HANDLE ,int ,int* );
typedef int WINAPI (*tf_PSSearch)(HANDLE ,int ,int , int , int , int *,int *);
typedef int WINAPI (*tf_PSRegModule)(HANDLE ,int );
typedef int WINAPI (*tf_PSStoreChar)(HANDLE ,int ,int , int );
typedef int WINAPI (*tf_PSLoadChar)(HANDLE ,int ,int ,int );
typedef int WINAPI (*tf_PSUpChar)(HANDLE ,int ,int , unsigned char* , int* );
typedef int WINAPI (*tf_PSDownChar)(HANDLE ,int ,int , unsigned char* , int );
typedef int WINAPI (*tf_PSDownChar_Test)(HANDLE ,int ,int , unsigned char* , int ,int ,int ,WORD ,WORD ,int );
typedef int WINAPI (*tf_PSUpImage)(HANDLE ,int ,unsigned char* , int* );
typedef int WINAPI (*tf_PSDownImage)(HANDLE ,int ,unsigned char *, int );
typedef int WINAPI (*tf_PSImgData2BMP)(unsigned char* ,const char* );
typedef int WINAPI (*tf_PSGetImgDataFromBMP)(HANDLE ,const char *,unsigned char *,int *);
typedef int WINAPI (*tf_PSDelChar)(HANDLE ,int ,int ,int );
typedef int WINAPI (*tf_PSEmpty)(HANDLE ,int );
typedef int WINAPI (*tf_PSReadParTable)(HANDLE ,int ,unsigned char* );
typedef int WINAPI (*tf_PSReadInfPage)(HANDLE ,int , unsigned char* );
typedef int WINAPI (*tf_PSHighSpeedSearch)(HANDLE ,int ,int , int , int , int *,int *);
typedef int WINAPI (*tf_PSTemplateNum)(HANDLE ,int ,int *);
typedef int WINAPI (*tf_PSGenBinImage)(HANDLE ,int , int );
typedef int WINAPI (*tf_PSPowerDown)(HANDLE ,int );
typedef int WINAPI (*tf_PSSetPwd)(HANDLE ,int ,unsigned char* );
typedef int WINAPI (*tf_PSVfyPwd)(HANDLE ,int ,unsigned char* );
typedef int WINAPI (*tf_PSReset)(HANDLE ,int );
typedef int WINAPI (*tf_PSReadInfo)(HANDLE ,int ,int ,unsigned char* );
typedef int WINAPI (*tf_PSWriteInfo)(HANDLE ,int ,int ,unsigned char* );
typedef int WINAPI (*tf_PSEnroll)(HANDLE ,int ,int* );
typedef int WINAPI (*tf_PSWriteReg)(HANDLE ,int ,int ,int );
typedef int WINAPI (*tf_PSSetBaud)(HANDLE ,int ,int );
typedef int WINAPI (*tf_PSSetSecurLevel)(HANDLE ,int ,int );
typedef int WINAPI (*tf_PSSetPacketSize)(HANDLE ,int ,int );
typedef int WINAPI (*tf_PSUpChar2File)(HANDLE ,int ,int , const char* );
typedef int WINAPI (*tf_PSDownCharFromFile)(HANDLE ,int ,int , const char* );
typedef int WINAPI (*tf_PSGetRandomData)(HANDLE ,int ,unsigned char* );
typedef int WINAPI (*tf_PSSetChipAddr)(HANDLE ,int ,unsigned char* );
typedef int WINAPI (*tf_PSIdentify)(HANDLE ,int ,int *);
typedef int WINAPI (*tf_PSDoUserDefine)(HANDLE ,int ,int ,int );
typedef int WINAPI (*tf_PSUpdatOnline)(HANDLE ,int ,unsigned char *, int );
typedef int WINAPI (*tf_PSBurnCode)(HANDLE ,int ,int ,unsigned char *, int );
typedef int WINAPI (*tf_PSPortControl)(HANDLE ,int ,BOOL );
typedef int WINAPI (*tf_PSFingerData2BMPData)(unsigned char *, unsigned char *,int* );
typedef int WINAPI (*tf_PSShowFingerData)(HWND ,unsigned char *);
typedef int WINAPI (*tf_PSReadIndexTable)(HANDLE ,int ,int ,unsigned char* );
typedef int WINAPI (*tf_PS_SB)(HANDLE ,int ,unsigned char *,int ,unsigned char *,int *,int );